stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - VERSION=18.16.1
    - docker build -t $DOCKER_USERNAME/node-rpm:$VERSION .
    - docker images
    - docker push $DOCKER_USERNAME/node-rpm:$VERSION
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG
